/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ForgeOss);
  }
}(this, function(expect, ForgeOss) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ForgeOss.ObjectsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ObjectsApi', function() {
    describe('copyTo', function() {
      it('should call copyTo successfully', function(done) {
        //uncomment below and update the code to test copyTo
        //instance.copyTo(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSignedResource', function() {
      it('should call createSignedResource successfully', function(done) {
        //uncomment below and update the code to test createSignedResource
        //instance.createSignedResource(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteObject', function() {
      it('should call deleteObject successfully', function(done) {
        //uncomment below and update the code to test deleteObject
        //instance.deleteObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSignedResource', function() {
      it('should call deleteSignedResource successfully', function(done) {
        //uncomment below and update the code to test deleteSignedResource
        //instance.deleteSignedResource(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getObject', function() {
      it('should call getObject successfully', function(done) {
        //uncomment below and update the code to test getObject
        //instance.getObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getObjectDetails', function() {
      it('should call getObjectDetails successfully', function(done) {
        //uncomment below and update the code to test getObjectDetails
        //instance.getObjectDetails(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getObjects', function() {
      it('should call getObjects successfully', function(done) {
        //uncomment below and update the code to test getObjects
        //instance.getObjects(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSessionid', function() {
      it('should call getSessionid successfully', function(done) {
        //uncomment below and update the code to test getSessionid
        //instance.getSessionid(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSignedResource', function() {
      it('should call getSignedResource successfully', function(done) {
        //uncomment below and update the code to test getSignedResource
        //instance.getSignedResource(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadChunk', function() {
      it('should call uploadChunk successfully', function(done) {
        //uncomment below and update the code to test uploadChunk
        //instance.uploadChunk(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadObject', function() {
      it('should call uploadObject successfully', function(done) {
        //uncomment below and update the code to test uploadObject
        //instance.uploadObject(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadSignedResource', function() {
      it('should call uploadSignedResource successfully', function(done) {
        //uncomment below and update the code to test uploadSignedResource
        //instance.uploadSignedResource(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadSignedResourcesChunk', function() {
      it('should call uploadSignedResourcesChunk successfully', function(done) {
        //uncomment below and update the code to test uploadSignedResourcesChunk
        //instance.uploadSignedResourcesChunk(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
